### ISSUE TITLE
args and kwargs in new plotting routines have the same name

### ISSUE THREAD

**Issue by jroettenbacher** [lacros-tropos/larda#15]
Hi all, while working with the new *2 plotting routines from Willi I noticed that, when handing kwargs to the functions, I get a type error:
`Traceback (most recent call last):
File "<input>", line 20, in <module>
File "/projekt1/remsens/work/jroettenbacher/Base/larda/pyLARDA/Transformations.py", line 3173, in plot_timeheight2
    axis, cont = _add_contour(axis, fontsize=pdata['fontsize'], **kwargs)
TypeError: _add_contour() got multiple values for keyword argument 'fontsize'`

Here is a small example. Just change the path to larda and connect to any campaign you have access to:

```python
import sys
sys.path.append("/projekt1/remsens/work/jroettenbacher/Base/larda")
import pyLARDA
import datetime as dt
import logging
log = logging.getLogger('pyLARDA')
log.setLevel(logging.INFO)
log.addHandler(logging.StreamHandler())

larda = pyLARDA.LARDA().connect("eurec4a")

begin_dt = dt.datetime(2020, 1, 20, 0, 0, 0)
end_dt = begin_dt + dt.timedelta(hours=23, minutes=59, seconds=59)
time_interval = [begin_dt, end_dt]

# read in data
radar_ze = larda.read("LIMRAD94", "Ze", time_interval, [0, 'max'])
fig, ax = pyLARDA.Transformations.plot_timeheight2(radar_ze, range_interval=[0, 2000],
                                                   z_converter='lin2z',
                                                   rg_converter=False,
                                                   title=f"Issue title",
                                                   fontsize=16)
```

The culprit is `fontsize` as it is used internally by another function (see error message). This also happens with other keywords.
I'm not sure how big that problem is. But one solution could be to name internal args with a leading underscore like the internal functions:
`fontsize` -> `_fontsize`
This would keep readability and should not be too difficult. 
Just wanted to open this as a issue to notify everyone. If you agree with my solution I would change the internal args as I keep experiencing these errors.
Best Johannes

**Comment by martin-rdz** [comment]
Thanks for bringing up that issue.
I think internal variables with `_` are not the optimal solution, as the whole point is to be able to overwrite 
certain settings via `kwargs` to the top level function. 
Manually popping the keys in question might be more transparent `kwargs.pop('figsize')` (see `def plot_timeseries2` in a9717ef6cf0c5caf4430911af6eb15e).
Maybe @KarlJohnsonnn has more insight? 

- Martin

**Comment by jroettenbacher** [comment]
Hmm, I understand your point. 
I like the idea of manually popping keywords, after they've been read out of the kwargs dictionary. I will do it that way then.
