### ISSUE TITLE
Ignore wrong time stamps for plotting

### ISSUE THREAD

**Issue by HolgerPollyNet** [lacros-tropos/larda#38]
As discussed, it would be great to have a functionality to allow plotting, even though there are some issue with the time stamps.

I used data from PollyNET from cvo (campaign'pollyxt_cpv'):

dt_begin = datetime.datetime(2024,8,15)
dt_end=datetime.datetime(2024,9,15)
POLLY_bsc=larda.read("POLLYNET","attbsc532", [dt_begin, dt_end], [15000, 25000])

afterwards putting to xarray:
POLLY_bscx=pyLARDA.Transformations.container2DataArray(POLLY_bsc)

After that, reshaping does not work, because:
"ValueError: index must be monotonic for resampling"

Plotting the times lead to:
fig, ax = plt.subplots()
ax.plot(POLLY_bsc['ts'])
![Unbenannt](https://github.com/user-attachments/assets/2fccd3c2-cefd-4e72-8376-329e00d4bdae)
 and clearly showing some "dips".

**Comment by HolgerPollyNet** [comment]
Unfortunately, I have not the right to assign someone ;-) @ulysses78

**Comment by ulysses78** [comment]
This issue was solved in the merge of pull request #40.
